---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        rtpengine_version: "{{ lookup('env', 'RTPENGINE_VERSION') }}"

    - name: Install prerequisites
      block:
        - name: Update apt cache
          when: ansible_os_family == "Debian"
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false

        - name: Install Dependencies
          package:
            name: "{{ item }}"
            state: present
          with_items:
            - rsyslog
            - nftables

        - name: Start and Enable nftables service
          systemd:
            name: nftables
            enabled: true
            state: started

  roles:
    - role: ansible-role-rtpengine
      tags:
        - rtpengine
